// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dapos.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/dapos.proto

It has these top-level messages:
	Transaction
	TransactionResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	Hash       []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From       string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To         string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Value      int64  `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	Time       int64  `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	DelegateId int64  `protobuf:"varint,6,opt,name=delegateId" json:"delegateId,omitempty"`
	Type       int64  `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto1.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Transaction) GetDelegateId() int64 {
	if m != nil {
		return m.DelegateId
	}
	return 0
}

func (m *Transaction) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type TransactionResponse struct {
	T *Transaction `protobuf:"bytes,1,opt,name=t" json:"t,omitempty"`
}

func (m *TransactionResponse) Reset()                    { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string            { return proto1.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()               {}
func (*TransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionResponse) GetT() *Transaction {
	if m != nil {
		return m.T
	}
	return nil
}

func init() {
	proto1.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto1.RegisterType((*TransactionResponse)(nil), "proto.TransactionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DAPoSGrpc service

type DAPoSGrpcClient interface {
	BroadcastTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error)
	ReceiveTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type dAPoSGrpcClient struct {
	cc *grpc.ClientConn
}

func NewDAPoSGrpcClient(cc *grpc.ClientConn) DAPoSGrpcClient {
	return &dAPoSGrpcClient{cc}
}

func (c *dAPoSGrpcClient) BroadcastTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/proto.DAPoSGrpc/BroadcastTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAPoSGrpcClient) ReceiveTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/proto.DAPoSGrpc/ReceiveTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DAPoSGrpc service

type DAPoSGrpcServer interface {
	BroadcastTransaction(context.Context, *Transaction) (*TransactionResponse, error)
	ReceiveTransaction(context.Context, *Transaction) (*TransactionResponse, error)
}

func RegisterDAPoSGrpcServer(s *grpc.Server, srv DAPoSGrpcServer) {
	s.RegisterService(&_DAPoSGrpc_serviceDesc, srv)
}

func _DAPoSGrpc_BroadcastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).BroadcastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/BroadcastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).BroadcastTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAPoSGrpc_ReceiveTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).ReceiveTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/ReceiveTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).ReceiveTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _DAPoSGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DAPoSGrpc",
	HandlerType: (*DAPoSGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastTransaction",
			Handler:    _DAPoSGrpc_BroadcastTransaction_Handler,
		},
		{
			MethodName: "ReceiveTransaction",
			Handler:    _DAPoSGrpc_ReceiveTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dapos.proto",
}

func init() { proto1.RegisterFile("proto/dapos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x8f, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0x87, 0x5f, 0xa7, 0x4d, 0x5f, 0xf5, 0x8a, 0x90, 0x38, 0x3a, 0x58, 0x1d, 0x50, 0x94, 0x29,
	0x53, 0x91, 0xca, 0xc0, 0x0c, 0x42, 0xfc, 0xd9, 0x90, 0xe1, 0x0b, 0x98, 0xe4, 0xa0, 0x91, 0xda,
	0x9c, 0x65, 0x1f, 0x95, 0xfa, 0x61, 0x98, 0xf8, 0xa2, 0xa8, 0xd7, 0x0e, 0x41, 0xb0, 0x31, 0xf9,
	0xe7, 0xe7, 0xfc, 0x9c, 0xef, 0xe0, 0x24, 0x44, 0x16, 0x3e, 0x6f, 0x7c, 0xe0, 0x34, 0xd7, 0x8c,
	0xb9, 0x1e, 0xe5, 0xa7, 0x81, 0xc9, 0x73, 0xf4, 0x5d, 0xf2, 0xb5, 0xb4, 0xdc, 0x21, 0xc2, 0x70,
	0xe9, 0xd3, 0xd2, 0x9a, 0xc2, 0x54, 0x47, 0x4e, 0xf3, 0x8e, 0xbd, 0x46, 0x5e, 0xdb, 0xac, 0x30,
	0xd5, 0xd8, 0x69, 0xc6, 0x63, 0xc8, 0x84, 0xed, 0x40, 0x49, 0x26, 0x8c, 0x53, 0xc8, 0x37, 0x7e,
	0xf5, 0x4e, 0x76, 0x58, 0x98, 0x6a, 0xe0, 0xf6, 0x97, 0x9d, 0x29, 0xed, 0x9a, 0x6c, 0xae, 0x50,
	0x33, 0x9e, 0x01, 0x34, 0xb4, 0xa2, 0x37, 0x2f, 0xf4, 0xd0, 0xd8, 0x91, 0x56, 0x7a, 0x44, 0x9d,
	0x6d, 0x20, 0xfb, 0xff, 0xe0, 0x6c, 0x03, 0x95, 0x97, 0x70, 0xda, 0x1b, 0xd2, 0x51, 0x0a, 0xdc,
	0x25, 0xc2, 0x02, 0x8c, 0xe8, 0xa4, 0x93, 0x05, 0xee, 0xd7, 0x9a, 0xf7, 0x9f, 0x19, 0x59, 0x7c,
	0x18, 0x18, 0xdf, 0x5c, 0x3d, 0xf2, 0xd3, 0x5d, 0x0c, 0x35, 0xde, 0xc3, 0xf4, 0x3a, 0xb2, 0x6f,
	0x6a, 0x9f, 0xe4, 0xdb, 0xd2, 0x3f, 0xe5, 0xd9, 0xec, 0x97, 0x86, 0x87, 0x7f, 0xcb, 0x7f, 0x78,
	0x0b, 0xe8, 0xa8, 0xa6, 0x76, 0x43, 0x7f, 0xea, 0xf3, 0x32, 0xd2, 0xe2, 0xc5, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x0b, 0xee, 0x80, 0xe2, 0xa1, 0x01, 0x00, 0x00,
}
