// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/txChannel.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/txChannel.proto

It has these top-level messages:
	Transaction
	TransactionResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	Hash       []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From       string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To         string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Value      int64  `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	Time       int64  `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	DelegateId int64  `protobuf:"varint,6,opt,name=delegateId" json:"delegateId,omitempty"`
	Type       int64  `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto1.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Transaction) GetDelegateId() int64 {
	if m != nil {
		return m.DelegateId
	}
	return 0
}

func (m *Transaction) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type TransactionResponse struct {
	T *Transaction `protobuf:"bytes,1,opt,name=t" json:"t,omitempty"`
}

func (m *TransactionResponse) Reset()                    { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string            { return proto1.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()               {}
func (*TransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionResponse) GetT() *Transaction {
	if m != nil {
		return m.T
	}
	return nil
}

func init() {
	proto1.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto1.RegisterType((*TransactionResponse)(nil), "proto.TransactionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TxChannel service

type TxChannelClient interface {
	BroadcastTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error)
	ReceiveTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type txChannelClient struct {
	cc *grpc.ClientConn
}

func NewTxChannelClient(cc *grpc.ClientConn) TxChannelClient {
	return &txChannelClient{cc}
}

func (c *txChannelClient) BroadcastTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/proto.TxChannel/BroadcastTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txChannelClient) ReceiveTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/proto.TxChannel/ReceiveTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TxChannel service

type TxChannelServer interface {
	BroadcastTransaction(context.Context, *Transaction) (*TransactionResponse, error)
	ReceiveTransaction(context.Context, *Transaction) (*TransactionResponse, error)
}

func RegisterTxChannelServer(s *grpc.Server, srv TxChannelServer) {
	s.RegisterService(&_TxChannel_serviceDesc, srv)
}

func _TxChannel_BroadcastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxChannelServer).BroadcastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TxChannel/BroadcastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxChannelServer).BroadcastTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxChannel_ReceiveTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxChannelServer).ReceiveTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TxChannel/ReceiveTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxChannelServer).ReceiveTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _TxChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TxChannel",
	HandlerType: (*TxChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastTransaction",
			Handler:    _TxChannel_BroadcastTransaction_Handler,
		},
		{
			MethodName: "ReceiveTransaction",
			Handler:    _TxChannel_ReceiveTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/txChannel.proto",
}

func init() { proto1.RegisterFile("proto/txChannel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0xb4, 0xa9, 0x74, 0x2a, 0x1e, 0xc6, 0x0a, 0x4b, 0x0f, 0x12, 0x72, 0xca, 0xa9,
	0x42, 0x3d, 0x78, 0x57, 0x10, 0xbd, 0x2e, 0x7d, 0x81, 0x35, 0x19, 0x4d, 0x20, 0xdd, 0x09, 0xd9,
	0xb1, 0xd8, 0x87, 0xf1, 0xe4, 0x8b, 0x4a, 0xa7, 0x15, 0x22, 0x7a, 0xf3, 0xb4, 0xff, 0xfc, 0xb3,
	0xdf, 0xcc, 0xfc, 0x70, 0xd9, 0xf5, 0x2c, 0x7c, 0x2d, 0xef, 0xf7, 0xb5, 0x0f, 0x81, 0xda, 0xa5,
	0xd6, 0x98, 0xea, 0x93, 0x7f, 0x1a, 0x98, 0xad, 0x7b, 0x1f, 0xa2, 0x2f, 0xa5, 0xe1, 0x80, 0x08,
	0xe3, 0xda, 0xc7, 0xda, 0x9a, 0xcc, 0x14, 0x67, 0x4e, 0xf5, 0xde, 0x7b, 0xe9, 0x79, 0x63, 0x93,
	0xcc, 0x14, 0x53, 0xa7, 0x1a, 0xcf, 0x21, 0x11, 0xb6, 0x23, 0x75, 0x12, 0x61, 0x9c, 0x43, 0xba,
	0xf5, 0xed, 0x1b, 0xd9, 0x71, 0x66, 0x8a, 0x91, 0x3b, 0x14, 0x7b, 0x52, 0x9a, 0x0d, 0xd9, 0x54,
	0x4d, 0xd5, 0x78, 0x05, 0x50, 0x51, 0x4b, 0xaf, 0x5e, 0xe8, 0xa9, 0xb2, 0x13, 0xed, 0x0c, 0x1c,
	0x65, 0x76, 0x1d, 0xd9, 0xd3, 0x23, 0xb3, 0xeb, 0x28, 0xbf, 0x85, 0x8b, 0xc1, 0x91, 0x8e, 0x62,
	0xc7, 0x21, 0x12, 0x66, 0x60, 0x44, 0x2f, 0x9d, 0xad, 0xf0, 0x10, 0x6b, 0x39, 0xfc, 0x66, 0x64,
	0xf5, 0x61, 0x60, 0xba, 0xfe, 0x4e, 0x8e, 0x8f, 0x30, 0xbf, 0xeb, 0xd9, 0x57, 0xa5, 0x8f, 0xf2,
	0x23, 0xf4, 0x6f, 0x78, 0xb1, 0xf8, 0x63, 0xe0, 0x71, 0x6f, 0x7e, 0x82, 0x0f, 0x80, 0x8e, 0x4a,
	0x6a, 0xb6, 0xf4, 0xaf, 0x39, 0xcf, 0x13, 0x6d, 0xde, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0xca,
	0x9f, 0x44, 0xdd, 0xa5, 0x01, 0x00, 0x00,
}
